name: Snakemake linting check

on: 
  push:

env:
  PIXI_VERSION: v0.72.2

jobs:
  Tests:
    runs-on: ubuntu-latest
    environment: github-actions-snakemake-linting
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e  # v0.10.2
        with:
          pixi-version: ${{ env.PIXI_VERSION }}
          cache: true

      - name: Run linting
        run: pixi run --locked lint --check
