name: Snakemake linting check

on: 
  push:

env:
  PIXI_VERSION: v0.72.2

jobs:
  Tests:
    runs-on: ubuntu-latest
    environment: github-actions-snakemake-linting
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@14c8aabd75893f83f4ab30c03e7cf853c8208961  # v0.8.10
        with:
          pixi-version: ${{ env.PIXI_VERSION }}
          cache: true

      - name: Run linting
        run: pixi run --locked lint --check
